### PR TITLE
.seen and other goodness

### PR DESCRIPTION
**Pull request by jphase**
Added .seen command
Removed .rtfm command
Added nickchange event handler (for seen command)
Added human-readable diffdate() utility function in doc-bot.php to give date string between two dates

### CODE REVIEW

**Comment by jphase** [comment]
Fixing my last fail on the date diff command - mixed start and end date in datediff() method :-1:

**Comment by jphase** [comment]
Added .tell command
Added nickchange handlers to fix SmartIRC
Added in_channel() utility method to doc-bot.php because I don't trust SmartIRC's
Added check_messages() method to to doc-bot.php check for messages from .tell

**Comment by Clorith** [comment]
Wow, that's a lot of changes in one request.

It's going ot need a refres hfirst of all (it can't be merged cleanly at this time, most likely because you've not updated from master here).

It would also be beneficial to do one pull per function, it makes it a lot easier to audit at that point, as right now there's just too many things going on.

Some initial feedback though:
- You've made diffdate() but PHP already bundles a diff function with ti's DateTime class which may be nice to use
- Your .tell command performs DB queries on every join, this hsould be redundant as we can hold messages for users in memory as a better solution (populate it on init from the database of course)
- A fair amount of your use of the SmartIRC global variables can be replaced with the IRC class helper functions (for example `$irc->isJoined()` to look up users in channel)

**Comment by Clorith** [comment]
Closed as tehre's been no followup in some time

**Pull request closed without merging**
